### ISSUE TITLE
How do you create GCM Feedback objects?

### ISSUE THREAD

**Issue by jim0020** [9to5/pushr-gcm#2]
The APNS side of the house provides ConfigurationApnsFeedback.create to define a feedback object in Redis.  How do we do the same for GCM?  I don't see any feedback running for Gcm, so I assume I need to create a Feedback object in Redis.

**Comment by tompesman** [comment]
APNS has a separate protocol where the feedback is queued until you fetch it (not in sandbox mode). This is where the ApnsFeedback service is for. GCM works differently, it directly responds with the feedback upon sending a message. Therefore it doesn't need a separate feedback service.
